import { Injectable, Logger } from '@nestjs/common';

@Injectable()
export class ResponseCompletenessValidatorService {
  private readonly logger = new Logger(ResponseCompletenessValidatorService.name);

  // List of prepositions and conjunctions that indicate a sentence is cut off when trailing
  private readonly incompleteSuffixes = [
    'ke',
    'ki',
    'ka',
    'ko',
    'se',
    'aur',
    'ya',
    'bhi',
    'hi',
    'toh',
    'tha',
    'thi',
    'the',
    'kar',
    'le',
    'and',
    'but',
    'or',
    'with',
    'of',
    'to',
    'for',
    'because',
    'about',
    'kripya',
    'please',
  ];

  /**
   * Evaluates if a generated response ends abruptly or contains a trailing connective,
   * and heals it to ensure a complete, natural customer experience.
   *
   * @param text The response string generated by the AI
   * @param defaultQuestion Optional default follow-up question to append if healed
   * @returns Cleaned and completed conversational text
   */
  validateAndHeal(text: string, defaultQuestion?: string): string {
    if (!text || text.trim() === '') return '';

    let cleaned = text.trim();

    // 1. Remove trailing ellipsis or abrupt trailing symbols
    cleaned = cleaned.replace(/\s*\.{2,}\s*$/g, '');

    // Get the last word of the sentence
    const words = cleaned.split(/\s+/);
    if (words.length === 0) return cleaned;

    const lastWordRaw = words[words.length - 1];
    // Strip trailing punctuation from the last word to inspect it
    const lastWord = lastWordRaw.replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?"']/g, '').toLowerCase();

    // 2. Check if the sentence ends in a connective fragment
    if (this.incompleteSuffixes.includes(lastWord)) {
      this.logger.warn(`Truncation detected: sentence ended abruptly on connective "${lastWordRaw}"`);

      // Remove the trailing connective word
      words.pop();
      cleaned = words.join(' ').trim();

      // Ensure it ends with clean sentence-ending punctuation or a comma
      if (!/[.!?]$/.test(cleaned)) {
        cleaned += '.';
      }

      // 3. Append follow-up context to restore user engagement
      if (defaultQuestion) {
        cleaned += ` ${defaultQuestion}`;
      } else {
        cleaned += ' Kya aap iske baare mein aur jaanana chahte hain?';
      }

      this.logger.log(`Truncated text healed successfully: "${cleaned}"`);
    } else {
      // If the text does not end with a clean sentence-ending punctuation, add a period
      if (!/[.!?]$/.test(cleaned) && words.length > 2) {
        cleaned += '.';
      }
    }

    return cleaned;
  }
}
